version: 2
jobs:
  backend_format:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          command: |
            cd backend
            pipenv install --skip-lock
            pipenv install --skip-lock --dev
            pipenv run black . --check
  backend_test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          command: |
            cd backend
            pipenv install --skip-lock
            pipenv install --skip-lock --dev
            pipenv run pytest
  frontend_format:
    docker:
      - image: node:8.4.0
    steps:
      - checkout
      - run:
          command: |
            cd c2tc-mobile
            yarn
            yarn format
workflows:
  version: 2
  build-test:
    jobs:
      - backend_format
      - backend_test
      - frontend_format
